sude: false
language: c
addons:
  apt:
    packages:
      - rake
      - bison
      - git
      - gperf
compiler:
  - gcc
  - clang
env:
  - MRUBY_VERSION=1.4.1
  - MRUBY_VERSION=master
matrix:
  allow_failures:
    - env: MRUBY_VERSION=master
script:
  - rake test
